CREATE DATABASE IF NOT EXISTS login_oop;

CREATE TABLE if NOT EXISTS pengguna(
	idUser INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50),
	password_user VARCHAR(50)
);



SELECT * FROM pengguna

DELETE FROM pengguna WHERE idUser IS NULL;

ALTER TABLE pengguna 
MODIFY idUser INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (idUser);